import {
  Geist,
  Geist_Mono,
  Montserrat,
  Outfit,
  Lexend,
  Poppins,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
// import { Toaster } from "react-hot-toast";
// import { Bounce, ToastContainer } from "react-toastify";
const inter = Lexend({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <Toaster position="top-center" className="text-[13px]" /> */}
        {/* <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        /> */}
        <Toaster  richColors />
      </body>
    </html>
  );
}
